# .github/workflows/3.1-python-tests.yml
name: 'Reuseable: Python Unit Tests'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-python-tests:
    name: 'Run Python Unit Tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Wir legen eine spezifische Python-Version fest

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install azure-identity azure-mgmt-resource azure-mgmt-compute azure-mgmt-monitor

      - name: 'Run VM module unit test'
        run: |
          python tests/test_find_vms.py
